[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_AUTH0_DOMAIN,AUTH0_CLIENT_ID,AUTH0_ISSUER_BASE_URL"
  SECRETS_SCAN_OMIT_PATHS = "dist/_headers,dist/assets/**"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.auth0.com https://cdn.lrkt-in.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://rsms.me;
      img-src 'self' data: https:;
      font-src 'self' data: https://fonts.gstatic.com https://rsms.me;
      connect-src 'self' https://api.openai.com https://generativelanguage.googleapis.com https://*.supabase.co https://*.auth0.com https://cdn.auth0.com;
      frame-ancestors 'none';
      manifest-src 'self';
    """
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200