[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  VITE_APP_VERSION = "$npm_package_version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200