# Netlify configuration for OncoVista React/TypeScript SPA

[build]
  # Use the standard build script - Netlify handles dependency installation
  command = "npm run build"
  # Directory to publish - Vite outputs to 'dist' by default
  publish = "dist"
  # Functions directory for server-side AI endpoints
  functions = "netlify/functions"

[build.environment]
  # Node.js version for build
  NODE_VERSION = "18"
  # NPM configuration for legacy peer dependencies
  NPM_FLAGS = "--legacy-peer-deps --no-audit"
  # Build optimization
  NODE_OPTIONS = "--max-old-space-size=4096"

# Environment variables for production
[context.production.environment]
  VITE_NODE_ENV = "production"
  VITE_AUTH0_DOMAIN = "mvoncovista.us.auth0.com"
  VITE_AUTH0_CLIENT_ID = "your-auth0-client-id"
  VITE_AUTH0_AUDIENCE = "https://mvoncovista.us.auth0.com/api/v2/"
  VITE_AUTH0_REDIRECT_URI = "https://oncovista.netlify.app"
  VITE_AUTH0_CALLBACK_URL = "https://oncovista.netlify.app/callback"
  VITE_GOOGLE_AI_API_KEY = "your-google-ai-api-key"
  VITE_API_BASE_URL = "https://oncovista.netlify.app/.netlify/functions"

# Environment variables for preview/branch deploys
[context.deploy-preview.environment]
  VITE_NODE_ENV = "development"
  VITE_AUTH0_DOMAIN = "dev-bqgm5fdnyx1sdqja.us.auth0.com"
  VITE_AUTH0_CLIENT_ID = "your-dev-auth0-client-id"
  VITE_AUTH0_AUDIENCE = "https://dev-bqgm5fdnyx1sdqja.us.auth0.com/api/v2/"
  VITE_AUTH0_REDIRECT_URI = "https://deploy-preview-*--oncovista.netlify.app"
  VITE_AUTH0_CALLBACK_URL = "https://deploy-preview-*--oncovista.netlify.app/callback"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# API routes to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # HTTPS Security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
    # Content Security Policy for OncoVista with Auth0 and Google AI
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        https://cdn.auth0.com 
        https://js.auth0.com 
        https://generativelanguage.googleapis.com;
      style-src 'self' 'unsafe-inline' 
        https://fonts.googleapis.com 
        https://cdn.auth0.com;
      font-src 'self' 
        https://fonts.gstatic.com 
        https://cdn.auth0.com;
      img-src 'self' data: blob: 
        https://*.gravatar.com 
        https://*.auth0.com 
        https://s.gravatar.com;
      connect-src 'self' 
        https://mvoncovista.us.auth0.com 
        https://dev-bqgm5fdnyx1sdqja.us.auth0.com 
        https://generativelanguage.googleapis.com 
        https://api.oncovista.com 
        wss://oncovista.netlify.app;
      frame-src 'self' 
        https://mvoncovista.us.auth0.com 
        https://dev-bqgm5fdnyx1sdqja.us.auth0.com;
      object-src 'none';
      media-src 'self';
      worker-src 'self' blob:;
      child-src 'self';
      form-action 'self' 
        https://mvoncovista.us.auth0.com 
        https://dev-bqgm5fdnyx1sdqja.us.auth0.com;
      base-uri 'self';
    '''

# Static asset caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML caching (shorter duration for SPA)
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"

# Service Worker caching
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# API response headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://oncovista.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"

# Medical data compliance headers (HIPAA considerations)
[[headers]]
  for = "/api/patients/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    Pragma = "no-cache"
    Expires = "0"

# Error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/500"
  to = "/500.html"
  status = 500

# Health check endpoint
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# Maintenance mode (uncomment when needed)
# [[redirects]]
#   from = "/*"
#   to = "/maintenance.html"
#   status = 503
#   force = true
#   conditions = {Role = ["maintenance"]}

# Branch-specific configurations
[context.branch-deploy]
  command = "npm run build"

[context.branch-deploy.environment]
  VITE_NODE_ENV = "staging"