# Netlify configuration for OncoVista React/TypeScript SPA

[build]
  # Build command - install all dependencies (including dev deps for build tools like TypeScript)
  command = "npm ci --include=dev && npm run build"
  
  # Directory to publish - Vite outputs to 'dist' by default
  publish = "dist"
  
  # Functions directory for server-side AI endpoints
  functions = "netlify/functions"

[build.environment]  # Specify Node.js version for consistent builds
  NODE_VERSION = "20.11.0"
  # Use npm ci for faster, reliable installs in CI
  NPM_FLAGS = "--prefer-offline --no-audit --no-fund"
  # Enable corepack for package manager compatibility
  COREPACK_ENABLE_STRICT = "0"

  # Environment variables (add your specific ones here)
  # NODE_ENV = "production"  # Don't set this during build as it prevents devDependencies installation  GENERATE_SOURCEMAP = "false"
  # Secrets scanning configuration - exclude build output and omit known client-safe keys
  SECRETS_SCAN_OMIT_PATHS = "dist/**,src/**,node_modules/**,.env,*.md,package.json,package-lock.json"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_AUTH0_CLIENT_ID,VITE_AUTH0_DOMAIN,AUTH0_DOMAIN,AUTH0_CLIENT_ID,VITE_SUPABASE_URL"
  SECRETS_SCAN_ENABLED = "false"

# Build processing settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# SPA redirects - Essential for React Router to work properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
  # Optional: Add conditions to exclude API routes or assets if needed
  # conditions = {Role = ["admin"]}

# Security headers for enhanced protection
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent the site from being embedded in frames (clickjacking protection)
    X-Frame-Options = "DENY"
    
    # Enable XSS protection in older browsers
    X-XSS-Protection = "1; mode=block"
      # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
      # Control referrer information
    Referrer-Policy = "same-origin"
      # Content Security Policy - Comprehensive configuration for Auth0, fonts, and APIs
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        https://cdn.auth0.com 
        https://dev-bqgm5fdnyx1sdqja.us.auth0.com 
        https://dev-bqqm5fdnyx1sdqja.us.auth0.com 
        https://mvoncovista.us.auth0.com;
      style-src 'self' 'unsafe-inline' 
        https://fonts.googleapis.com 
        https://rsms.me;
      img-src 'self' data: https: blob:
        https://dev-bqgm5fdnyx1sdqja.us.auth0.com 
        https://dev-bqqm5fdnyx1sdqja.us.auth0.com 
        https://mvoncovista.us.auth0.com 
        https://cdn.auth0.com
        https://s.gravatar.com
        https://www.gravatar.com
        https://secure.gravatar.com;
      font-src 'self' data: 
        https://fonts.gstatic.com 
        https://rsms.me;
      connect-src 'self' 
        https://api.openai.com 
        https://generativelanguage.googleapis.com 
        https://*.supabase.co 
        https://dev-bqgm5fdnyx1sdqja.us.auth0.com 
        https://dev-bqqm5fdnyx1sdqja.us.auth0.com 
        https://mvoncovista.us.auth0.com 
        https://cdn.auth0.com;
      frame-src 'self' 
        https://dev-bqgm5fdnyx1sdqja.us.auth0.com 
        https://dev-bqqm5fdnyx1sdqja.us.auth0.com 
        https://mvoncovista.us.auth0.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' 
        https://dev-bqgm5fdnyx1sdqja.us.auth0.com 
        https://dev-bqqm5fdnyx1sdqja.us.auth0.com 
        https://mvoncovista.us.auth0.com;
    """
    
    # Permissions Policy (formerly Feature Policy)
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache control for static assets (CSS, JS, images)
[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache static assets for 1 year since they have hash-based names
    Cache-Control = "public, max-age=31536000, immutable"
    
    # Enable CORS for assets if needed
    Access-Control-Allow-Origin = "*"

# Cache control for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    # Cache HTML for 5 minutes to allow quick updates
    Cache-Control = "public, max-age=300, must-revalidate"

# Cache control for service worker (if you add one later)
[[headers]]
  for = "/sw.js"
  [headers.values]
    # Don't cache service worker
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache control for API-like endpoints (if you add any)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Optimize fonts if you're using custom fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Handle favicon and manifest files
[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/json"

# Custom error pages (optional)
# [[redirects]]
#   from = "/404"
#   to = "/404.html"
#   status = 404

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  # Production Auth0 URLs
  VITE_AUTH0_CALLBACK_URL = "https://mwoncovista.com/callback"
  VITE_AUTH0_REDIRECT_URI = "https://mwoncovista.com"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "true"
  # Deploy preview URLs (Netlify will inject the actual URL)
  VITE_AUTH0_CALLBACK_URL = "https://deploy-preview-${REVIEW_ID}--mwoncovista.com/callback"
  VITE_AUTH0_REDIRECT_URI = "https://deploy-preview-${REVIEW_ID}--mwoncovista.com"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  GENERATE_SOURCEMAP = "true"
  # Branch deploy URLs (Netlify will inject the actual URL)
  VITE_AUTH0_CALLBACK_URL = "https://${BRANCH}--mwoncovista.com/callback"
  VITE_AUTH0_REDIRECT_URI = "https://${BRANCH}--mwoncovista.com"

# Form handling (if you have contact forms)
# [form]
#   name = "contact"
#   action = "/thank-you"
#   method = "POST"
